services:
    #  --------------------------------------------
    backend-goals-manag:
      build:
        context: ./goals-management
        dockerfile: Dockerfile
      container_name: goals-manag
      depends_on:
        mysql-goals-manag:
          condition: service_healthy
      ports:
        - "1114:8080"
      networks:
        - red_microservicios
    #  --------------------------------------------
    mysql-goals-manag:
      build:
        context: ./MySQL
        dockerfile: Dockerfile
      container_name: mysql-goals-manag
      volumes:
        - ./MySQL/mysql_data:/var/lib/mysql
      ports:
        - "1113:3306"
      networks:
        - red_microservicios
      healthcheck:
        test: [ "CMD","mysql", "-u", "sdgrh", "-psdgrh123*" ]
        interval: 30s
        timeout: 10s
        retries: 5
    #  --------------------------------------------
    adminer-goals-manag:
      image: adminer
      container_name: adminer-goals-manag
      depends_on:
        - mysql-goals-manag
      ports:
        - "1112:8080"
      networks:
        - red_microservicios
  #  --------------------------------------------
networks:
  red_microservicios:
    external: true